# Python - Numpy

In [1]:
# Importar numpy
import numpy as np

In [3]:
from IPython.display import HTML
HTML('<iframe src=http://www.springer.com/mathematics/computational+science+%26+engineering/book/978-3-642-54958-8 width=600 height=350></iframe>')

In [4]:
HTML('<iframe src=http://www.numpy.org/ width=600 height=350></iframe>')  

In [2]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [3]:
help(np.matrix)

Help on class matrix in module numpy.matrixlib.defmatrix:

class matrix(numpy.ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the default), or whether a view is
 |     constructed.
 |  
 |  See Also
 |  --------
 |  array
 |  
 |  Examples
 |  --------
 |  >>> a = np.matrix('1 2; 3 4')
 |  >>> print a
 |  [[1 2]
 |   [3 4]]
 |  
 |  >

## Arrays

In [6]:
lista=[[i for i in range(5)] for j in range(10)]
print lista

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [7]:
lista[0][3]

3

In [11]:
print "Para convertir una lista en un array usar la función array"
lista=[1,2,3,4,5]
arr= np.array(lista)

print "Una lista de listas se convierte automáticamente en un array de varios índices"
n_points = 5
lista=[[0 for i in range(n_points)] for j in range(n_points)]
arr=np.array(lista)
print arr
print "Para referenciar un elemento de un array se le entrega una tupla de índices."
for i in range(n_points):
    arr[i,i] = 1.0
print arr

Para convertir una lista en un array usar la función array
Una lista de listas se convierte automáticamente en un array de varios índices
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Para referenciar un elemento de un array se le entrega una tupla de índices.
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:
print "Para inicializar un arreglo puede usarse la función zeros. Los números son float por defecto pero puede especificarse que sean enteros."
arr = np.zeros(10)
print "arr",arr


arrint=np.zeros(10,dtype=int)
print "arrint", arrint

Para inicializar un arreglo puede usarse la función zeros. Los números son float por defecto pero puede especificarse que sean enteros.
arr [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
arrint [0 0 0 0 0 0 0 0 0 0]


In [17]:
print "Esta función también puede utilizarse para inicializar arreglos de dos o más índices"
arr2 = np.zeros((n_points,n_points))

print "arr2", arr2

arr3=np.zeros((2,5,5))
print "arr3", arr3

Esta función también puede utilizarse para inicializar arreglos de dos o más índices
arr2 [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
arr3 [[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [20]:
print "La función linspace puede usarse para construir arrays con números igualmente espaciados en un intervalo"
arr=np.linspace(0,0.5,21)
print arr

La función linspace puede usarse para construir arrays con números igualmente espaciados en un intervalo
[ 0.     0.025  0.05   0.075  0.1    0.125  0.15   0.175  0.2    0.225
  0.25   0.275  0.3    0.325  0.35   0.375  0.4    0.425  0.45   0.475  0.5  ]


In [26]:
print "Los arrays son también objetos iterables."
L = 1.0
x =np.linspace(0,L/2.0,21)
y = np.sqrt((L/2.0)**2 - x**2)
print x
print y

Los arrays son también objetos iterables.
[ 0.     0.025  0.05   0.075  0.1    0.125  0.15   0.175  0.2    0.225
  0.25   0.275  0.3    0.325  0.35   0.375  0.4    0.425  0.45   0.475  0.5  ]
[ 0.5         0.49937461  0.49749372  0.494343    0.48989795  0.48412292
  0.4769696   0.46837485  0.45825757  0.44651428  0.4330127   0.41758233
  0.4         0.3799671   0.35707142  0.33071891  0.3         0.26339134
  0.21794495  0.15612495  0.        ]


## Vectorización

"Vectorization is very important for speeding up Python programs where we do heavy computations with arrays. Moreover, vectorization gives more compact code that is easier to read." Langtangen

In [15]:
datos=random.rand(10000)
def function(x):
    return log(x)
%timeit resultados=[function(x) for x in datos]
%timeit resultados=function(datos)

100 loops, best of 3: 8.28 ms per loop
1000 loops, best of 3: 424 µs per loop


In [16]:
def duplicador(x):
    return 2*x

In [17]:
lista = range(5)
print "duplicador(lista) duplica la lista"
print duplicador(lista)

arr = array(lista)
print "duplicador(arr) entrega otro array con la función aplicada a cada elemento."
print duplicador(arr)


duplicador(lista) duplica la lista
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
duplicador(arr) entrega otro array con la función aplicada a cada elemento.
[0 2 4 6 8]


In [19]:
# No todas las funciones se vectorizan automáticamente
def escalon(x):
    if x<0:
        return 0.
    else:
        return 1.
escalon(linspace(-1,1,3))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
# Puede usarse la función vectorize, que no es muy eficiente, para vectorizar la función
escalonvec = vectorize(escalon)
escalonvec(linspace(-1,1,10))

array([ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.])

In [21]:
# O volver a escribir la función usando las funciónes de numpy
def escalon2(x):
    return where(x<0,0,1)
escalon2(linspace(-1,1,10))

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])