# Movimiento en dos dimensiones

Uno de los grandes logros de la física moderna fue la realización, por parte de Galileo, de que el movimiento de un cuerpo en dos o tres
dimensiones, puede entenderse como la composición de movimientos diferentes, uno por cada eje de coordenadas. En otras palabras, se considera que el cuerpo ejecuta un movimiento en el eje *x* y otro aparte en el *y*, y que el movimiento total es la suma vectorial de estos dos.

En esta sección vamos a extraer una enorme ventaja de este hecho para escribir de forma muy sencilla las ecuaciones de movimiento de un objeto en dos dimensiones. Para ello vamos a usar la librería Numpy, como se describe a continuación.

## Arreglos multidimensionales de Numpy

Numpy es una librería especializada en la creación y manipulación de *arreglos* de varias dimensiones. Los arreglos se crean a partir de una lista de la siguiente forma:

In [1]:
li1 = [1, 2]

In [2]:
import numpy as np

In [5]:
a1 = np.array(li1)

In [6]:
a1

array([1, 2])

Estos arreglos se prefieren a las listas para representar cantidades vectoriales, debido a que cumplen con las siguientes propiedades:

**(1)**. Al multiplicar un número por un arreglo, se multiplican todos sus elementos

In [7]:
a1 * 3

array([3, 6])

In [8]:
5 * a1

array([ 5, 10])

Para las listas en cambio, esta operación hace que se repitan sus elementos, como ustedes recordarán:

In [9]:
li1 * 3

[1, 2, 1, 2, 1, 2]

**(2)**. Al sumar dos arreglos, se suman uno a uno sus elementos

In [10]:
a2 = np.array([3, -2])

In [11]:
a1 + a2

array([4, 0])

In [12]:
a2 - a1

array([ 2, -4])

En cambio, para las listas el signo `+` las concatena, mientas que el `-` arroja un error:

In [13]:
li2 = [3, -2]

In [14]:
li1 + li2

[1, 2, 3, -2]

In [16]:
li2 - li1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

Además de esto, Numpy tiene varias funciones adicionales para operar sobre vectores, como las siguientes:

* `np.dot`, para calcular el producto punto (o escalar) de dos vectores.

In [17]:
np.dot(a1, a2)

-1

* `np.cross`, para calcular el producto cruz (o vectorial) de dos vectores.

In [18]:
np.cross([1, 2, 3], [4, 5, 6])

array([-3,  6, -3])

* `np.linalg.norm`, para calcular la norma de un vector.

In [19]:
np.linalg.norm(a1)

2.2360679774997898

# Simulación del movimiento de una partícula en 2D usando Numpy

Lo realmente interesante de usar arreglos de Numpy viene al momento de simular el movimiento de un objeto en dos o tres dimensiones, pues lo único que debe cambiarse en los programas anteriores (que estaban hechos para una dimensión) son los valores de las condiciones iniciales. Los algoritmos de Euler o Verlet, con los que calculamos cómo se mueve el objeto a partir de estas condiciones, van a
quedar exactamente como antes!

Mirémoslo por medio de un ejemplo. Para simular el movimiento de una partícula en dos dimensiones, empezamos por definir su posición inicial como:

```python
p0 = np.array([0, 8])
```

Esto quiere decir que va a arrancar del punto con coordenadas $(x, y) = (0, 8)$.

A continuación definimos su velocidad inicial como:

```python
v0 = np.array([5, -3])
```

lo que implica que hacemos que se mueva en la dirección positiva del eje $x$ con velocidad de 5 m/s, y en la dirección negativa del eje $y$ con una velocidad de 3 m/s.

Finalmente definimos su aceleración inicial como:

```python
a0 = np.array([0, -9.8])
```

para especificar que la partícula sólo siente una fuerza en el eje $y$, debida a la gravedad.

Por su parte, vamos a seguir guardando el conjunto de posiciones, velocidades y aceleraciones en una lista, y no un arreglo, ya que *no* necesitamos que sean cantidades vectoriales:

```python
posiciones = [p0]
velocidades = [v0]
aceleraciones = [a0]
```

Esto es todo lo que se necesita cambiar para pasar de simular el movimiento en una dimensión al de dos. Como mencioné arriba, el algoritmo de Verlet queda *exactamente* como estaba antes, lo cual es posible debido a las propiedades de los arreglos de Numpy descritas arriba.

Por ejemplo, para calcular la nueva posición de la partícula, escribimos la siguiente línea de código:

```python
nueva_posicion = posiciones[-1] + velocidades[-1]*dt + aceleraciones[-1]*(dt**2)/2
```

Dado que los elementos de `posiciones`, `velocidades` y `aceleraciones` son arreglos, lo que hace esta línea es multiplicar cada arreglo por el número que lo acompaña (por ejemplo, a `velocidades[-1]` lo multiplica por `dt`), y después suma los resultados componente a componente, es decir, suma el primer elemento de `posiciones` con los primeros de `velocidades` y de `aceleraciones`.

En otras palabras, lo que calcula esta línea para determinar la coordenada *x* de la nueva posición de la partícula es lo siguiente (asumiendo que `dt` vale 0.01):

```python
0 + 5*(0.01) + 0*(0.01**2)/2
```

que corresponde al valor de `nueva_posicion[0]`. Por su parte, el valor `nueva_posicion[1]` es:

```python
8 + (-3)*(0.01) + (-9.8)*(0.01**2)/2
```

De la misma forma se calculan los valores de `nueva_velocidad` y `nueva_aceleracion`.

## Problemas

### Problema 1

Modificar el código para simular el movimiento de la caída de una bola en una dimensión, para simular la caída de la misma en 2D, usando las instrucciones anteriores.

¿Cuál es el movimiento que se observa en este caso?

In [20]:
# Escribir la solución aquí


### Problema 2

Definir una función llamada `colision_muros` que determine si una partícula se ha chocado contra un muro ubicado en $x = 0$ o $y = 10$.

**Sugerencias**:

* Hacerlo de la misma forma en que se hizo para la caída de la bola, pero teniendo en cuenta la dirección en que se está moviendo la partícula, es decir, si es en $x$ o en $y$.

* Añadir a la condición del choque el que la velocidad debe ser negativa al chocar contra el muro en $x = 0$, y positiva en el de $y = 10$. Esto con el fin de evitar aplicar la condición de choque si la partícula sigue intersectada con el muro.

In [21]:
# Escribir la solución aquí
